/* Auto-generated by make_dmc_bank.py. */
/* MIDI CH11 maps notes 36..(36 + DMC_SAMPLE_COUNT - 1) to these samples. */
#ifndef V2B_DMC_SAMPLES_H
#define V2B_DMC_SAMPLES_H

#define DMC_SAMPLE_COUNT 26
static const DmcSample dmc_samples[DMC_SAMPLE_COUNT] = {
  {0x0F, 0xC0, 0x08, 0x0A}, /* 00 MIDI 36: NESBREAK_ 10-cw_amen_decay-4.dmc */
  {0x0F, 0xC3, 0x07, 0x06}, /* 01 MIDI 37: NESBREAK_ 11-cw_amen_decay-4.dmc */
  {0x0F, 0xC5, 0x07, 0x08}, /* 02 MIDI 38: NESBREAK_ 12-cw_amen_decay-4.dmc */
  {0x0F, 0xC7, 0x06, 0x06}, /* 03 MIDI 39: NESBREAK_ 13-cw_amen_decay-4.dmc */
  {0x0F, 0xC9, 0x06, 0x08}, /* 04 MIDI 40: NESBREAK_ 14-cw_amen_decay-4.dmc */
  {0x0F, 0xCB, 0x07, 0x08}, /* 05 MIDI 41: NESBREAK_ 15-cw_amen_decay-4.dmc */
  {0x0F, 0xCD, 0x06, 0x09}, /* 06 MIDI 42: NESBREAK_ 16-cw_amen_decay-4.dmc */
  {0x0F, 0xCF, 0x06, 0x09}, /* 07 MIDI 43: NESBREAK_ 17-cw_amen_decay-4.dmc */
  {0x0F, 0xD1, 0x07, 0x07}, /* 08 MIDI 44: NESBREAK_ 18-cw_amen_decay-4.dmc */
  {0x0F, 0xD3, 0x07, 0x0A}, /* 09 MIDI 45: NESBREAK_ 19-cw_amen_decay-4.dmc */
  {0x0F, 0xD5, 0x06, 0x06}, /* 10 MIDI 46: NESBREAK_ 20-cw_amen_decay-4.dmc */
  {0x0F, 0xD7, 0x06, 0x08}, /* 11 MIDI 47: NESBREAK_ 21-cw_amen_decay-4.dmc */
  {0x0F, 0xD9, 0x17, 0x09}, /* 12 MIDI 48: NESBREAK_ 22-cw_amen_decay-4.dmc */
  {0x0F, 0xDF, 0x07, 0x09}, /* 13 MIDI 49: NESBREAK_ 23-cw_amen_decay-4.dmc */
  {0x0F, 0xE1, 0x07, 0x0D}, /* 14 MIDI 50: NESBREAK_ 24-cw_amen_decay-4.dmc */
  {0x0F, 0xE3, 0x08, 0x05}, /* 15 MIDI 51: NESBREAK_ 25-cw_amen_decay-4.dmc */
  {0x0F, 0xE6, 0x07, 0x09}, /* 16 MIDI 52: NESBREAK_ 26-cw_amen_decay-4.dmc */
  {0x0F, 0xE8, 0x06, 0x05}, /* 17 MIDI 53: NESBREAK_ 27-cw_amen_decay-4.dmc */
  {0x0F, 0xEA, 0x07, 0x08}, /* 18 MIDI 54: NESBREAK_ 28-cw_amen_decay-4.dmc */
  {0x0F, 0xEC, 0x07, 0x0A}, /* 19 MIDI 55: NESBREAK_ 29-cw_amen_decay-4.dmc */
  {0x0F, 0xEE, 0x07, 0x08}, /* 20 MIDI 56: NESBREAK_ 30-cw_amen_decay-4.dmc */
  {0x0F, 0xF0, 0x08, 0x05}, /* 21 MIDI 57: NESBREAK_ 31-cw_amen_decay-4.dmc */
  {0x0F, 0xF3, 0x07, 0x08}, /* 22 MIDI 58: NESBREAK_ 33-cw_amen_decay-4.dmc */
  {0x0F, 0xF5, 0x07, 0x0A}, /* 23 MIDI 59: NESBREAK_ 34-cw_amen_decay-4.dmc */
  {0x0F, 0xF7, 0x07, 0x08}, /* 24 MIDI 60: NESBREAK_ 35-cw_amen_decay-4.dmc */
  {0x0F, 0xF9, 0x07, 0x0B}, /* 25 MIDI 61: NESBREAK_ cw_amen_decay.dmc */
};

#endif
